import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Header } from "./components/layout/header";
import { Footer } from "./components/layout/footer";
import { Inter, Roboto } from 'next/font/google'
import { ToastProvider } from "@radix-ui/react-toast";
import { Toast } from "@/components/ui/toast";
import { Toaster } from "@/components/ui/toaster";
import { LeftSidebar } from "./components/layout/left-sidebar";
import { MtgProvider } from "./contexts/mtgContext";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { RightSidebar } from "./components/layout/right-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} ${roboto.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ToastProvider>
            <MtgProvider>
              <TooltipProvider>
                <SidebarProvider defaultOpenLeft defaultOpenRight={false}>
                  <LeftSidebar />
                  <div className="flex flex-col w-full items-center justify-between
              min-h-screen"
                  >
                    <Header />
                    <main className="flex flex-1 max-w-screen-2xl w-full px-2">
                      <Toaster />
                      {children}
                    </main>
                    <Footer />
                  </div>
                  <RightSidebar />
                </SidebarProvider>
              </TooltipProvider>
            </MtgProvider>
          </ToastProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
